//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssignment
    {
        public int id { get; set; }
        public Nullable<int> amount { get; set; }
        public Nullable<int> loan { get; set; }
        public Nullable<int> idProduct { get; set; }
        public Nullable<int> idEmployee { get; set; }
        public Nullable<int> idAssignmentType { get; set; }
        public Nullable<int> idAnchorAssingment { get; set; }
        public string detail { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public Nullable<System.DateTime> upDateDate { get; set; }
        public Nullable<System.DateTime> deleteDate { get; set; }
        public string state { get; set; }
    }
}
