//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using Entity;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class HSCMEntities : DbContext
    {
        public HSCMEntities()
            : base("name=HSCMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAssignment> tblAssignment { get; set; }
        public virtual DbSet<tblAssignmentType> tblAssignmentType { get; set; }
        public virtual DbSet<tblCategory> tblCategory { get; set; }
        public virtual DbSet<tblCellar> tblCellar { get; set; }
        public virtual DbSet<tblCellarArea> tblCellarArea { get; set; }
        public virtual DbSet<tblContactInformation> tblContactInformation { get; set; }
        public virtual DbSet<tblDepartment> tblDepartment { get; set; }
        public virtual DbSet<tblDownloadAssignment> tblDownloadAssignment { get; set; }
        public virtual DbSet<tblEmployee> tblEmployee { get; set; }
        public virtual DbSet<tblFileManager> tblFileManager { get; set; }
        public virtual DbSet<tblLoanAssignment> tblLoanAssignment { get; set; }
        public virtual DbSet<tblLoanAssignmentFileManager> tblLoanAssignmentFileManager { get; set; }
        public virtual DbSet<tblProduct> tblProduct { get; set; }
        public virtual DbSet<tblProductFileManager> tblProductFileManager { get; set; }
        public virtual DbSet<tblProductProvider> tblProductProvider { get; set; }
        public virtual DbSet<tblProductType> tblProductType { get; set; }
        public virtual DbSet<tblProverContactInformation> tblProverContactInformation { get; set; }
        public virtual DbSet<tblProvider> tblProvider { get; set; }
        public virtual DbSet<tblTransaction> tblTransaction { get; set; }
        public virtual DbSet<tblTransactionConfigurate> tblTransactionConfigurate { get; set; }
        public virtual DbSet<tblTransactionType> tblTransactionType { get; set; }
        public virtual DbSet<tblTypePermission> tblTypePermission { get; set; }
        public virtual DbSet<tblUser> tblUser { get; set; }
        public virtual DbSet<tblUserConfiguration> tblUserConfiguration { get; set; }
        public virtual DbSet<tblUserType> tblUserType { get; set; }
    }
}
